import { EPlanetTerrains } from "@/app/types/terrains";

export default function getTerrainStyles(terrain: EPlanetTerrains): string {
  const terrainStyles: { [key in EPlanetTerrains]: string } = {
    [EPlanetTerrains.DESERT]: "#DEAC80",
    [EPlanetTerrains.ACID_POOLS]: "#F1F3C2",
    [EPlanetTerrains.CLIFFS]: "#D2A679",
    [EPlanetTerrains.SAVANNAHS]: "#F7E8C2",
    [EPlanetTerrains.ROCK]: "#B0B0B0",
    [EPlanetTerrains.MOUNTAINS]: "#A9AFA8",
    [EPlanetTerrains.SCRUBLANDS]: "#C3CEDB",
    [EPlanetTerrains.GLACIERS]: "#E6F2F8",
    [EPlanetTerrains.CANYONS]: "#E7B08B",
    [EPlanetTerrains.TUNDRA]: "#EDF6FA",
    [EPlanetTerrains.ROCKY_CANYONS]: "#C69C84",
    [EPlanetTerrains.FUNGUS_FORESTS]: "#C8A0C8",
    [EPlanetTerrains.JUNGLES]: "#A0D2A0",
    [EPlanetTerrains.SAVANNAS]: "#FFD88C",
    [EPlanetTerrains.CITYSCAPE]: "#B0C4DE",
    [EPlanetTerrains.GRASSY_HILLS]: "#D9F8A1",
    [EPlanetTerrains.SEAS]: "#A8D1E7",
    [EPlanetTerrains.ROCKY_DESERTS]: "#E7D4B5",
    [EPlanetTerrains.BARREN]: "#D8D8D8",
    [EPlanetTerrains.AIRLESS_ASTEROID]: "#C4C4C4",
    [EPlanetTerrains.FIELDS]: "#FFFDD0",
    [EPlanetTerrains.CAVES]: "#8F8F8F",
    [EPlanetTerrains.SWAMPS]: "#91A084",
    [EPlanetTerrains.ASH]: "#CBCBCB",
    [EPlanetTerrains.CITIES]: "#B3B3B3",
    [EPlanetTerrains.MESAS]: "#E0A88C",
    [EPlanetTerrains.MOUNTAIN_RANGES]: "#D3E0E0",
    [EPlanetTerrains.URBAN]: "#A8A8A8",
    [EPlanetTerrains.PLAINS]: "#F8F0D8",
    [EPlanetTerrains.VERDANT]: "#A8DCA0",
    [EPlanetTerrains.MOUNTAIN]: "#D1D1D1",
    [EPlanetTerrains.GRASSLANDS]: "#DAF8A8",
    [EPlanetTerrains.PLATEAUS]: "#D8B392",
    [EPlanetTerrains.VINES]: "#A3825A",
    [EPlanetTerrains.VOLCANOES]: "#FF8A7A",
    [EPlanetTerrains.ICE_CANYONS]: "#E8F7FF",
    [EPlanetTerrains.TOXIC_CLOUDSEA]: "#B087B0",
    [EPlanetTerrains.DESERTS]: "#FAE3B0",
    [EPlanetTerrains.ICE_CAVES]: "#DFF6FF",
    [EPlanetTerrains.ROCK_ARCHES]: "#B0A59E",
    [EPlanetTerrains.HILLS]: "#A9D4A0",
    [EPlanetTerrains.ROCKY]: "#B8B8B8",
    [EPlanetTerrains.RIVERS]: "#A0D1FF",
    [EPlanetTerrains.ROCKY_ISLANDS]: "#E0C9A6",
    [EPlanetTerrains.JUNGLE]: "#A1E3A1",
    [EPlanetTerrains.GAS_GIANT]: "#B0DFF8",
    [EPlanetTerrains.VALLEYS]: "#D6D6D6",
    [EPlanetTerrains.SWAMP]: "#A3B8A3",
    [EPlanetTerrains.ISLANDS]: "#FFD8A8",
    [EPlanetTerrains.FORESTS]: "#98D2A8",
    [EPlanetTerrains.LAVA_RIVERS]: "#FFAA9E",
    [EPlanetTerrains.REEFS]: "#A4E4D8",
    [EPlanetTerrains.BOGS]: "#B0A078",
    [EPlanetTerrains.OCEAN]: "#A0CCE8",
    [EPlanetTerrains.LAKES]: "#B3E0FF",
    [EPlanetTerrains.UNKNOWN]: "#B5B7C0",
    [EPlanetTerrains.RAINFORESTS]: "#88D0A0",
    [EPlanetTerrains.OCEANS]: "#A0D3D3",
    [EPlanetTerrains.GRASS]: "#B0E38E",
    [EPlanetTerrains.SINKHOLES]: "#C4DAD2",
  };

  return terrainStyles[terrain]|| "#b5b7c0";
}
